"""
Security pattern definitions for input validation

Defines dangerous patterns for XSS, SQL injection, and other attacks.
Extracted from app.utils.security to follow Single Responsibility Principle.
"""

from typing import List

# XSS and dangerous HTML patterns
DANGEROUS_PATTERNS: List[str] = [
    r'<script[^>]*>.*?</script>',
    r'javascript:',
    r'vbscript:',
    r'onload\s*=',
    r'onerror\s*=',
    r'onclick\s*=',
    r'eval\s*\(',
    r'expression\s*\(',
    r'url\s*\(',
    r'@import',
    r'behavior\s*:',
    r'-moz-binding',
    r'<iframe[^>]*>',
    r'<object[^>]*>',
    r'<embed[^>]*>',
    r'<link[^>]*>',
    r'<meta[^>]*>',
    r'<style[^>]*>',
    r'<form[^>]*>',
    r'<input[^>]*>',
    r'<textarea[^>]*>',
    r'<select[^>]*>',
    r'<button[^>]*>',
    r'<a[^>]*>',
    r'<img[^>]*>',
    r'<video[^>]*>',
    r'<audio[^>]*>',
    r'<source[^>]*>',
    r'<track[^>]*>',
    r'<canvas[^>]*>',
    r'<svg[^>]*>',
    r'<math[^>]*>',
    r'<applet[^>]*>',
    r'<param[^>]*>',
    r'<base[^>]*>',
    r'<area[^>]*>',
    r'<map[^>]*>',
    r'<frame[^>]*>',
    r'<frameset[^>]*>',
    r'<noframes[^>]*>',
    r'<noscript[^>]*>',
    r'<details[^>]*>',
    r'<summary[^>]*>',
    r'<dialog[^>]*>',
    r'<menu[^>]*>',
    r'<menuitem[^>]*>',
    r'<command[^>]*>',
    r'<keygen[^>]*>',
    r'<output[^>]*>',
    r'<progress[^>]*>',
    r'<meter[^>]*>',
    r'<datalist[^>]*>',
    r'<optgroup[^>]*>',
    r'<option[^>]*>',
    r'<fieldset[^>]*>',
    r'<legend[^>]*>',
    r'<label[^>]*>',
]

# SQL injection patterns
SQL_INJECTION_PATTERNS: List[str] = [
    r'union\s+select',
    r'select\s+.*\s+from',
    r'insert\s+into',
    r'update\s+.*\s+set',
    r'delete\s+from',
    r'drop\s+table',
    r'create\s+table',
    r'alter\s+table',
    r'exec\s*\(',
    r'execute\s*\(',
    r'sp_',
    r'xp_',
    r'--',
    r'/\*.*\*/',
    r'waitfor\s+delay',
    r'benchmark\s*\(',
    r'sleep\s*\(',
    r'pg_sleep\s*\(',
    r'load_file\s*\(',
    r'into\s+outfile',
    r'into\s+dumpfile',
    r'load\s+data\s+infile',
    r'\.\./',
    r'\.\.\\',
    r'char\s*\(',
    r'ascii\s*\(',
    r'ord\s*\(',
    r'chr\s*\(',
    r'concat\s*\(',
    r'substring\s*\(',
    r'substr\s*\(',
    r'mid\s*\(',
    r'left\s*\(',
    r'right\s*\(',
    r'length\s*\(',
    r'len\s*\(',
    r'count\s*\(',
    r'sum\s*\(',
    r'avg\s*\(',
    r'min\s*\(',
    r'max\s*\(',
    r'group\s+by',
    r'order\s+by',
    r'having\s+',
    r'where\s+',
    r'and\s+',
    r'or\s+',
    r'not\s+',
    r'like\s+',
    r'in\s*\(',
    r'between\s+',
    r'is\s+null',
    r'is\s+not\s+null',
    r'exists\s*\(',
    r'in\s+\(.*select',
    r'not\s+in\s+\(.*select',
    r'exists\s*\(.*select',
    r'not\s+exists\s*\(.*select',
    r'any\s*\(.*select',
    r'all\s*\(.*select',
    r'some\s*\(.*select',
    r'case\s+when',
    r'if\s*\(',
    r'ifnull\s*\(',
    r'coalesce\s*\(',
    r'nullif\s*\(',
    r'cast\s*\(',
    r'convert\s*\(',
    r'str_to_date\s*\(',
    r'date_format\s*\(',
    r'now\s*\(',
    r'curdate\s*\(',
    r'curtime\s*\(',
    r'year\s*\(',
    r'month\s*\(',
    r'day\s*\(',
    r'hour\s*\(',
    r'minute\s*\(',
    r'second\s*\(',
    r'week\s*\(',
    r'dayofweek\s*\(',
    r'dayofyear\s*\(',
    r'weekday\s*\(',
    r'quarter\s*\(',
    r'last_day\s*\(',
    r'makedate\s*\(',
    r'maketime\s*\(',
    r'period_add\s*\(',
    r'period_diff\s*\(',
    r'to_days\s*\(',
    r'to_seconds\s*\(',
    r'from_days\s*\(',
    r'from_unixtime\s*\(',
    r'unix_timestamp\s*\(',
    r'utc_date\s*\(',
    r'utc_time\s*\(',
    r'utc_timestamp\s*\(',
    r'time_to_sec\s*\(',
    r'sec_to_time\s*\(',
    r'time_format\s*\(',
    r'get_format\s*\(',
    r'date_add\s*\(',
    r'date_sub\s*\(',
    r'adddate\s*\(',
    r'subdate\s*\(',
    r'addtime\s*\(',
    r'subtime\s*\(',
    r'datediff\s*\(',
    r'timediff\s*\(',
]

# Profanity and inappropriate content list (note: this should ideally use a library)
# Keeping a minimal list here for essential filtering
INAPPROPRIATE_WORDS: List[str] = [
    'fuck', 'shit', 'bitch', 'ass', 'damn', 'crap', 'piss', 'dick', 'cock',
    'pussy', 'tits', 'boob', 'whore', 'slut', 'hoe', 'nigger', 'nigga',
    'chink', 'kike', 'spic', 'wetback', 'towelhead', 'raghead',
    'fag', 'faggot', 'dyke', 'tranny', 'retard',
]

# Reserved usernames
RESERVED_USERNAMES: List[str] = [
    'admin', 'administrator', 'root', 'user', 'guest', 'test', 'api',
    'www', 'mail', 'ftp', 'support', 'help', 'info', 'contact',
    'about', 'privacy', 'terms', 'legal', 'security', 'auth',
    'login', 'logout', 'register', 'signup', 'signin', 'signout',
    'password', 'reset', 'forgot', 'verify', 'confirm', 'activate',
    'deactivate', 'delete', 'remove', 'update', 'edit', 'create',
    'system', 'service', 'app', 'application', 'mobile', 'web',
]

# Weak passwords
WEAK_PASSWORDS: List[str] = [
    "password", "123456", "123456789", "qwerty", "abc123",
    "password123", "admin", "letmein", "welcome", "monkey"
]

# Character substitution patterns for obfuscation detection
OBFUSCATION_PATTERNS: List[tuple] = [
    (r'[0o]', 'o'),
    (r'[1i!l]', 'i'),
    (r'[3e]', 'e'),
    (r'[4a@]', 'a'),
    (r'[5s$]', 's'),
    (r'[6g]', 'g'),
    (r'[7t]', 't'),
    (r'[8b]', 'b'),
    (r'[9g]', 'g'),
    (r'[|!1]', 'i'),
    (r'[*]', ''),
    (r'[-_]', ''),
]

