[phases.setup]
nixPkgs = ["python313"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install --no-cache-dir -r requirements-lock.txt"
]

[start]
cmd = "python3 scripts/railway_start.py"

