"""
Nutrition Models Module

All nutrition-related models: nutrition tracking, goals, food items, advanced analysis
"""

# Nutrition models
from .nutrition import (
    NutritionCompatibilityLevel,
    NutritionalRequirementsBase,
    NutritionalRequirementsCreate,
    NutritionalRequirementsResponse,
    FoodAnalysisBase,
    FoodAnalysisCreate,
    NutritionalInfo,
    FoodAnalysisResponse,
    NutritionCompatibilityResponse,
    FeedingRecordBase,
    FeedingRecordCreate,
    FeedingRecordResponse,
    DailyNutritionSummaryBase,
    DailyNutritionSummaryResponse,
    MultiPetNutritionInsights,
    ComparativeInsight,
    NutritionAnalysisRequest,
    NutritionRecommendation,
    NutritionGoal,
)

# Food items models
from .food_items import (
    NutritionalInfoBase,
    FoodItemBase,
    FoodItemCreate,
    FoodItemUpdate,
    FoodItemResponse,
    FoodSearchRequest,
    FoodSearchResponse,
    FoodAnalysisResponse as FoodItemAnalysisResponse,
)

# Calorie goals models
from .calorie_goals import (
    CalorieGoalBase,
    CalorieGoalCreate,
    CalorieGoalUpdate,
    CalorieGoalResponse,
    CalorieGoalProgress,
)

# Advanced nutrition models
from .advanced_nutrition import (
    WeightGoalType,
    RecommendationPriority,
    RecommendationCategory,
    TrendDirection,
    TrendStrength,
    PetWeightRecordBase,
    PetWeightRecordCreate,
    PetWeightRecordResponse,
    PetWeightGoalBase,
    PetWeightGoalCreate,
    PetWeightGoalResponse,
    NutritionalTrendBase,
    NutritionalTrendResponse,
    WeightTrendAnalysis,
    FoodComparisonBase,
    FoodComparisonCreate,
    FoodComparisonResponse,
    FoodComparisonMetrics,
    AnalyticsType,
    NutritionalAnalyticsCacheBase,
    NutritionalAnalyticsCacheResponse,
    NutritionalRecommendationBase,
    NutritionalRecommendationCreate,
    NutritionalRecommendationResponse,
    WeeklyNutritionSummary,
    MonthlyTrendAnalysis,
    HealthInsights,
    NutritionalPatterns,
    WeightTrackingRequest,
    TrendAnalysisRequest,
    FoodComparisonRequest,
    AnalyticsRequest,
    AdvancedNutritionResponse,
    WeightManagementDashboard,
    NutritionalTrendsDashboard,
    FoodComparisonDashboard,
)

# Nutritional standards models
from .nutritional_standards import (
    Species,
    LifeStage,
    ActivityLevel,
    NutritionalStandardBase,
    NutritionalStandardCreate,
    NutritionalStandardUpdate,
    NutritionalStandardResponse,
    NutritionalRecommendation as StandardNutritionalRecommendation,
    NutritionalAnalysisRequest as StandardNutritionalAnalysisRequest,
)

__all__ = [
    # Nutrition models
    'NutritionCompatibilityLevel',
    'NutritionalRequirementsBase',
    'NutritionalRequirementsCreate',
    'NutritionalRequirementsResponse',
    'FoodAnalysisBase',
    'FoodAnalysisCreate',
    'NutritionalInfo',
    'FoodAnalysisResponse',
    'NutritionCompatibilityResponse',
    'FeedingRecordBase',
    'FeedingRecordCreate',
    'FeedingRecordResponse',
    'DailyNutritionSummaryBase',
    'DailyNutritionSummaryResponse',
    'MultiPetNutritionInsights',
    'ComparativeInsight',
    'NutritionAnalysisRequest',
    'NutritionRecommendation',
    'NutritionGoal',
    # Food items models
    'NutritionalInfoBase',
    'FoodItemBase',
    'FoodItemCreate',
    'FoodItemUpdate',
    'FoodItemResponse',
    'FoodSearchRequest',
    'FoodSearchResponse',
    'FoodItemAnalysisResponse',
    # Calorie goals models
    'CalorieGoalBase',
    'CalorieGoalCreate',
    'CalorieGoalUpdate',
    'CalorieGoalResponse',
    'CalorieGoalProgress',
    # Advanced nutrition models
    'WeightGoalType',
    'RecommendationPriority',
    'RecommendationCategory',
    'TrendDirection',
    'TrendStrength',
    'PetWeightRecordBase',
    'PetWeightRecordCreate',
    'PetWeightRecordResponse',
    'PetWeightGoalBase',
    'PetWeightGoalCreate',
    'PetWeightGoalResponse',
    'NutritionalTrendBase',
    'NutritionalTrendResponse',
    'WeightTrendAnalysis',
    'FoodComparisonBase',
    'FoodComparisonCreate',
    'FoodComparisonResponse',
    'FoodComparisonMetrics',
    'AnalyticsType',
    'NutritionalAnalyticsCacheBase',
    'NutritionalAnalyticsCacheResponse',
    'NutritionalRecommendationBase',
    'NutritionalRecommendationCreate',
    'NutritionalRecommendationResponse',
    'WeeklyNutritionSummary',
    'MonthlyTrendAnalysis',
    'HealthInsights',
    'NutritionalPatterns',
    'WeightTrackingRequest',
    'TrendAnalysisRequest',
    'FoodComparisonRequest',
    'AnalyticsRequest',
    'AdvancedNutritionResponse',
    'WeightManagementDashboard',
    'NutritionalTrendsDashboard',
    'FoodComparisonDashboard',
    # Nutritional standards models
    'Species',
    'LifeStage',
    'ActivityLevel',
    'NutritionalStandardBase',
    'NutritionalStandardCreate',
    'NutritionalStandardUpdate',
    'NutritionalStandardResponse',
    'StandardNutritionalRecommendation',
    'StandardNutritionalAnalysisRequest',
]

